### ISSUE TITLE
Image Content Mode

### ISSUE THREAD

**Issue by bryanbartow** [mcmatan/ImageOpenTransition#11]
Is there any reason that the ```contentMode``` property on the image copies in the ```animateTransitionObject``` methods is hard coded to ```.scaleAspectFill```?

If you're using any of the other modes on your images and any scaling is occurring, there is a noticeable "glitch" when the transition starts and the image copy is displayed.

Would it make sense to use the ```contentMode``` of ```viewToAnimateTo``` or ```viewToAnimateFrom```? For example:

``` Swift
assert(transitionObject.viewToAnimateFrom.image != nil, "Trying to animate with no Image")
        
let viewToAnimateFromCopy = UIImageView(image: transitionObject.viewToAnimateFrom.image!.copyMe())
viewToAnimateFromCopy.contentMode = transitionObject.viewToAnimateFrom.contentMode
        
viewToAnimateFromCopy.frame = transitionObject.viewToAnimateFrom.superview!.convert(transitionObject.viewToAnimateFrom.frame, to: containerView)
```

If so, I can submit a pull request.

**Comment by mcmatan** [comment]
Hi thanks for this, yes it seems logically current, if you can please submit a pull request it would be great (:

**Comment by bryanbartow** [comment]
@mcmatan Just submitted a PR.
