### ISSUE TITLE
Use of unresolved identifier "afterDelay"

### ISSUE THREAD

**Issue by JaDenis** [mcmatan/ImageOpenTransition#4]
doesn't build, where this afterDelay comes from?

good job, man! 👍  (no sarcasm)

**Comment by mcmatan** [comment]
Hi @JaDenis And thanks for the issue, the example project pod was not updated to the right submodule, For me the app did build any way.. just the animation was strange. I've pushed, and I'm resolving this issue, please inform me if this still happens after.

**Comment by JaDenis** [comment]
it's all good now! awesome stuff, man) i won't be using pod though, i like
it manually :)

2016-07-26 23:43 GMT+03:00 mcmatan notifications@github.com:
