### ISSUE TITLE
[!] Unable to find a specification for `ImageScaleTransition`

### ISSUE THREAD

**Issue by havocked** [mcmatan/ImageOpenTransition#5]
Using pod install with `pod 'ImageScaleTransition'` in my `Podfile`, I get this error:

`[!] Unable to find a specification for 'ImageScaleTransition'`

We should use `pod 'ImageOpenTransition'` right ? In that case the README.MD should be updated :)

**Comment by mcmatan** [comment]
Your right! Thanks for the issue, it was probebly changes by mistake.
