### ISSUE TITLE
Calling loadView() is discouraged

### ISSUE THREAD

**Issue by andres-ciano-umewin** [mcmatan/ImageOpenTransition#8]
As the [documentation](https://developer.apple.com/reference/uikit/uiviewcontroller/1621454-loadview) states, _"You should never call this method directly"_.
Is there another way to properly use the transitions when instantiating controllers from storyboard?

As of my current implementation (using `loadView()`), the transition works in some simple cases. However, in other more complex cases (ie with some sort of setup in `viewDidLoad()`), the destination controller fails to load if I use `loadView()`.

**Comment by mcmatan** [comment]
Hi, interesting topic, and thanks for the issue. Didn't know that was in the documentary.
You can use "loadViewIfNeeded" instead, I'll update the example project too.

**Comment by andres-ciano-umewin** [comment]
Perfect, using `loadViewIfNeeded()` works much better. I even realized that `viewDidLoad()` wasn't being called in the detail view, but it's working fine now.
Thanks!

**Comment by mcmatan** [comment]
Glad I could help (:
